Traceback (most recent call last):
  File "U:/project/Python/file.py", line 5, in <module>
    f2 = open("file2.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'file2.txt'
END
